rest-api:
  host: ""
  port:
  scheme: "http"
  endpoints:
    auth:
      sign-up: "/auth/registration"
      sign-in: "/auth/login"
    users:
      user: "/users/getUserInfo"
    subscriptions:
      available: "/subscriptions/allAvailable"
      current: "/subscriptions"