rest-api:
  host: ""
  port:
  scheme: "http"
  tokens:
    refresh-wait-timeout: 5
  endpoints:
    auth:
      sign-up: "/auth/registration"
      sign-in: "/auth/login"
      refresh: "/auth/refresh"
    users:
      user: "/users/getUserInfo"
      update: "/users"
    subscriptions:
      available: "/subscriptions/allAvailable"
      current: "/subscriptions"
      add: "/subscriptions"
      remove: "/subscriptions"
    analytics:
      by-query: "/analytics/history/{query}?depth={depth}"
      recent: "/analytics/byQuery"
logging:
  file:
    path: logs/
  level:
    ru.borshchevskiy.webui: DEBUG